// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/icq/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/ibc-go/v3/modules/core/02-client/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/tendermint/tendermint/abci/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgQuery defines a msg to send queries between
// ICQ enabled chains.
type MsgQuery struct {
	// the port on which the packet will be sent
	SourcePort string `protobuf:"bytes,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty" yaml:"source_port"`
	// the channel by which the packet will be sent
	SourceChannel string `protobuf:"bytes,2,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty" yaml:"source_channel"`
	// query reqeusts
	Requests []types.RequestQuery `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests"`
	// Timeout height relative to the current block height.
	// The timeout is disabled when set to 0.
	TimeoutHeight types1.Height `protobuf:"bytes,4,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height" yaml:"timeout_height"`
	// Timeout timestamp in absolute nanoseconds since unix epoch.
	// The timeout is disabled when set to 0.
	TimeoutTimestamp uint64 `protobuf:"varint,5,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty" yaml:"timeout_timestamp"`
}

func (m *MsgQuery) Reset()         { *m = MsgQuery{} }
func (m *MsgQuery) String() string { return proto.CompactTextString(m) }
func (*MsgQuery) ProtoMessage()    {}
func (*MsgQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f9afe72ee5ec491, []int{0}
}
func (m *MsgQuery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQuery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQuery.Merge(m, src)
}
func (m *MsgQuery) XXX_Size() int {
	return m.Size()
}
func (m *MsgQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQuery.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQuery proto.InternalMessageInfo

// MsgQueryResponse defines the MsgQuery response type.
type MsgQueryResponse struct {
}

func (m *MsgQueryResponse) Reset()         { *m = MsgQueryResponse{} }
func (m *MsgQueryResponse) String() string { return proto.CompactTextString(m) }
func (*MsgQueryResponse) ProtoMessage()    {}
func (*MsgQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f9afe72ee5ec491, []int{1}
}
func (m *MsgQueryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgQueryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgQueryResponse.Merge(m, src)
}
func (m *MsgQueryResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgQueryResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgQuery)(nil), "ibc.applications.icq.v1.MsgQuery")
	proto.RegisterType((*MsgQueryResponse)(nil), "ibc.applications.icq.v1.MsgQueryResponse")
}

func init() { proto.RegisterFile("ibc/applications/icq/v1/tx.proto", fileDescriptor_0f9afe72ee5ec491) }

var fileDescriptor_0f9afe72ee5ec491 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x3f, 0x6f, 0xd4, 0x30,
	0x18, 0xc6, 0x93, 0xde, 0x15, 0x1d, 0x3e, 0xb5, 0x2a, 0x16, 0x7f, 0xc2, 0x41, 0x93, 0x90, 0xe9,
	0x18, 0xb0, 0x95, 0xeb, 0x80, 0xd4, 0x05, 0x14, 0x16, 0x90, 0xa8, 0x04, 0x11, 0x2c, 0x08, 0xa9,
	0x24, 0xae, 0x95, 0xb3, 0x94, 0xc4, 0xb9, 0xd8, 0x89, 0xb8, 0x6f, 0xc0, 0xc8, 0x47, 0xe8, 0xc7,
	0xe9, 0xd8, 0x91, 0x29, 0x42, 0x77, 0x0b, 0xf3, 0xed, 0x48, 0xc8, 0x71, 0xd2, 0xf6, 0x06, 0xd4,
	0x29, 0xf6, 0xfb, 0xfc, 0x9e, 0xd7, 0xaf, 0xde, 0x3c, 0xc0, 0x65, 0x31, 0xc1, 0x51, 0x51, 0xa4,
	0x8c, 0x44, 0x92, 0xf1, 0x5c, 0x60, 0x46, 0x16, 0xb8, 0xf6, 0xb1, 0xfc, 0x8e, 0x8a, 0x92, 0x4b,
	0x0e, 0x1f, 0xb1, 0x98, 0xa0, 0x9b, 0x04, 0x62, 0x64, 0x81, 0x6a, 0x7f, 0x72, 0x3f, 0xe1, 0x09,
	0x6f, 0x19, 0xac, 0x4e, 0x1a, 0x9f, 0xd8, 0x84, 0x8b, 0x8c, 0x0b, 0x1c, 0x47, 0x82, 0xe2, 0xda,
	0x8f, 0xa9, 0x8c, 0x7c, 0x4c, 0x38, 0xcb, 0x3b, 0xdd, 0x51, 0x0f, 0x12, 0x5e, 0x52, 0x4c, 0x52,
	0x46, 0x73, 0xa9, 0xde, 0xd2, 0xa7, 0x0e, 0x78, 0x22, 0x69, 0x7e, 0x46, 0xcb, 0x8c, 0xe5, 0x12,
	0x47, 0x31, 0x61, 0x58, 0x2e, 0x0b, 0x2a, 0xb4, 0xe8, 0xfd, 0xdd, 0x01, 0xa3, 0x13, 0x91, 0x7c,
	0xac, 0x68, 0xb9, 0x84, 0x2f, 0xc1, 0x58, 0xf0, 0xaa, 0x24, 0xf4, 0xb4, 0xe0, 0xa5, 0xb4, 0x4c,
	0xd7, 0x9c, 0xde, 0x0d, 0x1e, 0x6e, 0x1a, 0x07, 0x2e, 0xa3, 0x2c, 0x3d, 0xf6, 0x6e, 0x88, 0x5e,
	0x08, 0xf4, 0xed, 0x03, 0x2f, 0x25, 0x7c, 0x0d, 0xf6, 0x3b, 0x8d, 0xcc, 0xa3, 0x3c, 0xa7, 0xa9,
	0xb5, 0xd3, 0x7a, 0x1f, 0x6f, 0x1a, 0xe7, 0xc1, 0x96, 0xb7, 0xd3, 0xbd, 0x70, 0x4f, 0x17, 0xde,
	0xe8, 0x3b, 0x7c, 0x05, 0x46, 0x25, 0x5d, 0x54, 0x54, 0x48, 0x61, 0x0d, 0xdc, 0xc1, 0x74, 0x3c,
	0x3b, 0x44, 0xd7, 0x73, 0x23, 0x35, 0x37, 0x0a, 0x35, 0xd0, 0xce, 0x1a, 0x0c, 0x2f, 0x1a, 0xc7,
	0x08, 0xaf, 0x4c, 0xf0, 0x1b, 0xd8, 0x97, 0x2c, 0xa3, 0xbc, 0x92, 0xa7, 0x73, 0xca, 0x92, 0xb9,
	0xb4, 0x86, 0xae, 0x39, 0x1d, 0xcf, 0x26, 0x48, 0xad, 0x5b, 0xed, 0x07, 0x75, 0x5b, 0xa9, 0x7d,
	0xf4, 0xb6, 0x25, 0x82, 0x43, 0xd5, 0xe3, 0x7a, 0xc4, 0x6d, 0xbf, 0x17, 0xee, 0x75, 0x05, 0x4d,
	0xc3, 0x77, 0xe0, 0x5e, 0x4f, 0xa8, 0xaf, 0x90, 0x51, 0x56, 0x58, 0xbb, 0xae, 0x39, 0x1d, 0x06,
	0x4f, 0x37, 0x8d, 0x63, 0x6d, 0x37, 0xb9, 0x42, 0xbc, 0xf0, 0xa0, 0xab, 0x7d, 0xea, 0x4b, 0xc7,
	0xa3, 0x1f, 0xe7, 0x8e, 0xf1, 0xe7, 0xdc, 0x31, 0x3c, 0x08, 0x0e, 0xfa, 0xf5, 0x87, 0x54, 0x14,
	0x3c, 0x17, 0x74, 0xf6, 0x15, 0x0c, 0x4e, 0x44, 0x02, 0x3f, 0x83, 0x5d, 0xfd, 0x5b, 0x9e, 0xa1,
	0xff, 0x24, 0x06, 0xf5, 0xd6, 0xc9, 0xf3, 0x5b, 0x91, 0xbe, 0x7b, 0xf0, 0xfe, 0x62, 0x65, 0x9b,
	0x97, 0x2b, 0xdb, 0xfc, 0xbd, 0xb2, 0xcd, 0x9f, 0x6b, 0xdb, 0xb8, 0x5c, 0xdb, 0xc6, 0xaf, 0xb5,
	0x6d, 0x7c, 0x99, 0x25, 0x4c, 0xce, 0xab, 0x18, 0x11, 0x9e, 0xe1, 0x2e, 0x74, 0x2c, 0x26, 0x2f,
	0x12, 0x8e, 0xeb, 0x23, 0x9c, 0xf1, 0xb3, 0x2a, 0xa5, 0x42, 0x45, 0x5b, 0x47, 0xba, 0x4d, 0x51,
	0x7c, 0xa7, 0x8d, 0xd1, 0xd1, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x19, 0x82, 0xcf, 0xf7,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// Query defines a rpc handler method for MsgQuery.
	Query(ctx context.Context, in *MsgQuery, opts ...grpc.CallOption) (*MsgQueryResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Query(ctx context.Context, in *MsgQuery, opts ...grpc.CallOption) (*MsgQueryResponse, error) {
	out := new(MsgQueryResponse)
	err := c.cc.Invoke(ctx, "/ibc.applications.icq.v1.Msg/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// Query defines a rpc handler method for MsgQuery.
	Query(context.Context, *MsgQuery) (*MsgQueryResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Query(ctx context.Context, req *MsgQuery) (*MsgQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ibc.applications.icq.v1.Msg/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Query(ctx, req.(*MsgQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.applications.icq.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Msg_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/applications/icq/v1/tx.proto",
}

func (m *MsgQuery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQuery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQuery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.TimeoutHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Requests) > 0 {
		for iNdEx := len(m.Requests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Requests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SourcePort) > 0 {
		i -= len(m.SourcePort)
		copy(dAtA[i:], m.SourcePort)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourcePort)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgQueryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgQueryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgQueryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgQuery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourcePort)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Requests) > 0 {
		for _, e := range m.Requests {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = m.TimeoutHeight.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.TimeoutTimestamp))
	}
	return n
}

func (m *MsgQueryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgQuery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQuery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQuery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourcePort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourcePort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requests = append(m.Requests, types.RequestQuery{})
			if err := m.Requests[len(m.Requests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TimeoutHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgQueryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgQueryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgQueryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
